[package]
name = "ecoz2"
version = "0.1.0"
authors = [
    "Carlos A. Rueda <carueda@mbari.org>",
]
description = "Linear Predictive Coding Vector Quantization and Hidden Markov Modeling for Pattern Recognition"
repository = "https://github.com/ecoz2/ecoz2rs"
license = "MIT OR Apache-2.0"
keywords = [
    "hmm",
    "hidden-markov-model",
    "linear-predictive-coding",
    "vector-quantization",
    "machine-learning",
]

# https://doc.rust-lang.org/cargo/reference/build-scripts.html
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]

csv = "1.1"
hound = "3.4.0"
itertools = "0.9.0"
libc = "0.2.62"
paw = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
structopt = { version = "0.3", features = [ "paw" ] }
walkdir = "2.3.1"

# https://stackoverflow.com/a/34054833/830737
[profile.dev]
opt-level = 3
