[package]
name = "ecoz2"
version = "0.1.0"

[dependencies]

structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"

sgn = { path = "sgn" }
lpc = { path = "lpc" }
prd = { path = "prd" }
vq = { path = "vq" }

# https://stackoverflow.com/a/34054833/830737
[profile.dev]
opt-level = 3
