[package]
name = "hmm"
version = "0.1.0"

[dependencies]

structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"

prd = { path = "../prd" }
utl = { path = "../utl" }

libc = "0.2.62"
