[package]
name = "seq"
version = "0.1.0"

[dependencies]

structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"

ecoz2_lib = { path = "../ecoz2_lib", version = "0.1.0" }
utl = { path = "../utl", version = "0.1.0" }
