[package]
name = "csvutil"
version = "0.1.0"

[dependencies]

csv = "1.1"

structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
