[package]
name = "lpc"
version = "0.1.0"

[dependencies]

structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"

sgn = { path = "../sgn" }
prd = { path = "../prd" }
